# This is a basic workflow to help you get started with Actions
name: .NET

on:
  schedule:
    - cron: "0 21 * * *"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      UseInMemoryDatabase: false

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - uses: ankane/setup-sqlserver@v1
      with:
        accept-eula: true
        sqlserver-version: 2022
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
      
    #- name: Appication Integration Tests
    #  run: dotnet test --no-build --verbosity normal
    #  working-directory: ./tests/MRA.Jobs.Api/Application.IntegrationTests
    
    #- name: Appication Unit Tests
    #  run: dotnet test --no-build --verbosity normal
    #  working-directory: ./tests/MRA.Jobs.Api/Application.UnitTests

    #- name: Application Domain Unit Tests
    #  run: dotnet test --no-build --verbosity normal
    #  working-directory: ./tests/MRA.Jobs.Api/Domain.UnitTests

    #- name: Application WebUI Acceptance Tests
    #  run: dotnet test --no-build --verbosity normal
    #  working-directory: ./tests/MRA.Jobs.Api/WebUI.AcceptanceTests
